// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK3iojBm8MFHSesKDgHnDxmX9TsBPQFvc',
    appId: '1:587505974347:web:1c092165ff1d7297b721ce',
    messagingSenderId: '587505974347',
    projectId: 'ta-solar',
    authDomain: 'ta-solar.firebaseapp.com',
    storageBucket: 'ta-solar.appspot.com',
    measurementId: 'G-MJRMW4H0YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY-5r7QIEbBzs4KyCvW7k7gyylkTBcsjs',
    appId: '1:587505974347:android:8a609cd9c4d74384b721ce',
    messagingSenderId: '587505974347',
    projectId: 'ta-solar',
    storageBucket: 'ta-solar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH-CNc6gmasUUnIgbThp1Sd3PHWskjdZE',
    appId: '1:587505974347:ios:b49197496d72de8cb721ce',
    messagingSenderId: '587505974347',
    projectId: 'ta-solar',
    storageBucket: 'ta-solar.appspot.com',
    iosClientId: '587505974347-vk8hd7uc39lv0pgpe1cumhp30vmb073u.apps.googleusercontent.com',
    iosBundleId: 'com.example.thesolarshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH-CNc6gmasUUnIgbThp1Sd3PHWskjdZE',
    appId: '1:587505974347:ios:2776dd4457145416b721ce',
    messagingSenderId: '587505974347',
    projectId: 'ta-solar',
    storageBucket: 'ta-solar.appspot.com',
    iosClientId: '587505974347-dp43t131q1ccva20d2blg5ngq3ut7iq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.thesolarshop.RunnerTests',
  );
}
